# programming language
language: python

# versions to test
python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch

# command to install dependencies
install:
  - python setup.py install

# command to run tests
script:
  - python -m youtube_dl_webui
